### ISSUE TITLE
Website crashed

### ISSUE THREAD

**Issue by kokjinsam** [loneleeandroo/meteor-polymerize#6]
Hi,

I really like using your polymer package. It's really convenient! I tried to deploy my app to meteor.com. Everything was fine but the website crashed when I visited the website. Here's the error that I got:

[Tue Jul 07 2015 03:26:05 GMT+0000 (UTC)] WARNING Error: EACCES, permission denied
'../../../../../../bower.json'
at Object.fs.openSync (fs.js:439:18)
at Object.fs.writeFileSync (fs.js:978:15)
at Bower.writeFile (packages/loneleeandroo:polymerize/polymerize-server.coffee:55:15)
at Bower.getFile (packages/loneleeandroo:polymerize/polymerize-server.coffee:40:10)
at new Bower (packages/loneleeandroo:polymerize/polymerize-server.coffee:23:25)
at new Polymerizer (packages/loneleeandroo:polymerize/polymerize-server.coffee:186:18)
at Package (packages/loneleeandroo:polymerize/polymerize-server.coffee:279:19)
at packages/loneleeandroo:polymerize/polymerize-server.coffee:1:1
at packages/loneleeandroo:polymerize/polymerize-server.coffee:1:1
at /meteor/containers/9b23dae6-02ba-be02-258a-13ac6e590eaf/bundle/programs/server/boot.js:222:10
[Tue Jul 07 2015 03:26:05 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Tue Jul 07 2015 03:26:05 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Tue Jul 07 2015 03:26:28 GMT+0000 (UTC)] INFO STATUS waiting -> killed
[Tue Jul 07 2015 03:26:28 GMT+0000 (UTC)] NOTICE Starting application on port 14954
[Tue Jul 07 2015 03:26:28 GMT+0000 (UTC)] INFO STATUS killed -> starting
[Tue Jul 07 2015 03:26:29 GMT+0000 (UTC)] INFO STATUS starting -> running
[Tue Jul 07 2015 03:26:30 GMT+0000 (UTC)] WARNING 
/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^

I'm not sure if this is related to the package. Can you please check? Thanks!

**Comment by eposschweiz** [comment]
Have the same problem

**Comment by horochovec** [comment]
+1
